### ISSUE TITLE
Tags not being output into .yml correctly.

### ISSUE THREAD

**Issue by furzeface** [ChrisMissal/generator-up-for-grabs#1]
When using the generator, entering comma-separated tags the output in the `.yml` file is as follows:
```yml
tags:
- 123,456,789,0
```
for example.

I've had a play around and figured that it's to do with the RegEx splitting the list [here](https://github.com/ChrisMissal/generator-up-for-grabs/blob/master/generators/app/index.js#L45).

I'm just wondering if that RegEx does anything majorly complex or it can be reduced to a string split on the comma? Changing it to `split(',');` gives the expected output from the generator:
```yml
tags:
- 123
- 456 
- 789
- 0
```
 but I didn't want to change it and submit a PR in case there was a particular reason for it.

Thanks! :octocat:

**Comment by ChrisMissal** [comment]
No real reason @furzeface, I was mostly using this as a chance to learn more about yeoman generators so feel free to submit a PR if you can!

**Comment by furzeface** [comment]
Ace, yeah I had a look into the regex for it, I reckon I can add to it -
the way I entered my tags into the prompt was different than it was
expecting but I can look at it, will do! :)

**Comment by ChrisMissal** [comment]
Closed by #2, thanks @furzeface! :tada:

**Comment by furzeface** [comment]
:octocat: :)
